### ISSUE TITLE
Sequence longer than what the ESM-2 trasnformer can encode entirely

### ISSUE THREAD

**Issue by myonaung** [UberClifford/BepiPred3.0-Predictor#1]
Hi,

May I know how can I get around the issues when I have very long  AA sequences . It  stops calculating after a certain length - specifically after 1023 positions.

**Comment by UberClifford** [comment]
Hi, 
Happy to see someone trying out BepiPred-3.0! There is protein size limit that the ESM-2 transformer can encode is 1023 positions. Since BepiPred-3.0 relies on the ESM-2 representation, it is limited by this as well.

**Comment by myonaung** [comment]
Thanks very much for the response. Very good resources for the community !
