### ISSUE TITLE
Access to esm_model_state_dict.pt or biolib docker

### ISSUE THREAD

**Issue by simoesrenato** [UberClifford/BepiPred3.0-Predictor#2]
Hi!
I'm trying to create a docker with Bepipred-3, however I can`t find the file/folder **esm_model_state_dict.pt .** which is described in the end of the [Dockerfile](https://github.com/UberClifford/BepiPred3.0-Predictor/blob/main/misc/biolib_bepipred3/Dockerfile).

**COPY esm_model_state_dict.pt .**  

Where can I find these file/folder or where can I download this prepared docker **local-docker://uberclifford/bepipred-3.0-biolib_v15:latest** used in biolib? I'm trying to embed the BepiPred3 into my [Pipeline](https://pubmed.ncbi.nlm.nih.gov/35571557/) in the new version. I'm trying this way instead run directly from biolib because it's not possible to use a biolib inside a container deployed in biolib server, so I have to customize the bepipred-3 docker to include my application inside and deploy a new version to biolib.

Thanks a lot!!

**Comment by UberClifford** [comment]
Hi,
The  esm_model_state_dict.pt  file is an artifact of when we were using the ESM-1b model for BepiPred-3.0
We are now using ESM-2 for BepiPred.3.0. 
I had not updated the dockerfile for this setup. I have updated the files now.

You will need to add the esm2_t33_650M_UR50D.pt and esm2_t33_650M_UR50D-contact-regression.pt 
to ./models file manually before you build docker image. 
You can get these from the facebookresearch/esm github.

I found that BepiPred-3.0 on biolib is down right now. But for a reason unrelated to the docker image.

I just re-tested building the docker image and running it.  Work for me.
After building, you can test it by running, 
docker run <whatever tag you used> python3 bepipred3_CLI.py -o output_directory -pred vt_pred -add_seq_len -i example_antigens.fasta

Let me know if it works out for you :)!

**Comment by simoesrenato** [comment]
Hi!

I couldn't find the file e**sm2_t33_650M_UR50D-contact-regression.pt** only [esm2_t33_650M_UR50D](https://dl.fbaipublicfiles.com/fair-esm/models/esm2_t33_650M_UR50D.pt). 
Do you have the download direct link for this file? Or is this file generated by some script with esm2_t33_650M_UR50D as input? 

I built the docker only with **esm2_t33_650M_UR50D.pt** file (just for a test purpose haha) and I got the error: FileNotFoundError: [Errno 2] No such file or directory: '/models/esm2_t33_650M_UR50D-contact-regression.pt'.

We're almost there! 

Thank you!!

**Comment by simoesrenato** [comment]
Hi, here is some updates:

I downloaded esm2_t33_650M_UR50D-contact-regression.pt file from [here](https://dl.fbaipublicfiles.com/fair-esm/regression/esm2_t33_650M_UR50D-contact-regression.pt). Thus, I got the 2 required files.

The command to copy the folder /esm_encodings/ is missing in Dockerfile, so I added the follow:

```
RUN mkdir /esm_encodings/
ADD esm_encodings /esm_encodings/
```

So I built with the command: 

`docker build .`

The build was successful and then I executed the command:

`docker run -i -t _<image id>_ python3 bepipred3_CLI.py -o output_directory -pred vt_pred -add_seq_len -i example_antigens.fasta`

I got the follow error (I'm reporting because some people can face the same):

```
_GPU device not detected. Using CPU: cpu
Directory for esm encodings already there. Saving encodings there.
Number of sequences detected in fasta file: 15
ESM-2 encoding sequences...
ESM model could not be run with following error message: Command '['python', PosixPath('/usr/local/lib/python3.8/dist-packages/bp3/extract.py'), PosixPath('/models/esm2_t33_650M_UR50D.pt'), PosixPath('/esm_encodings/antigens.fasta'), PosixPath('/esm_encodings'), '--include', 'per_tok']' died with <Signals.SIGKILL: 9>..
This is likely a memory issue._

```
I changed the docker RAM memory from 2GB to 4GB and voila!

```
docker run -i -t <id image> python3 bepipred3_CLI.py -o output_directory -pred vt_pred -add_seq_len -i example_antigens.fasta
GPU device not detected. Using CPU: cpu
Directory for esm encodings already there. Saving encodings there.
Number of sequences detected in fasta file: 15
ESM-2 encoding sequences...
Read /esm_encodings/antigens.fasta with 15 sequences
Processing 1 of 2 batches (14 sequences)
Processing 2 of 2 batches (1 sequences)
Directory B-cell epitope predictions already there. Saving results there.
Directory for saving plots already there. Saving results there.
Creating figures
Click 'Download' to get the result files
```

Thanks a lot!

Best regards

**Comment by UberClifford** [comment]
Hi, 
Awesome that you were able to figure it out. 
The ./esm_encodings directory is created on run time, if it does not already exist.
So it doesn't have to be in the build file. 
Thanks for the info on the docker RAM memory. 

Good luck in your research!
